//字符串对象
	match()
		就是用来检索一个字符串是否存在
		存在返回要检索的字符串，不存在返回null
	search()
		用于检索字符串中指定的子字符串或检索与正则表达式相匹配的子字符串
	indexOf()
		可返回某个指定的字符串值在字符串中首次出现的位置
	replace()
		在字符串中用一些字符替换另一些字符，或者替换一个与正则表达式匹配的子串
		//stringObject.replace(原字符,替换字符)    
		//stringObject.replace(正则表达式,替换字符) 
	charAt()
		获取字符串中的某一个字符
	toLowerCase()
		将大写字符串转换为小写字符串
	toUpperCase()
		将小写字符串转换为大写字符串
	concat()
		连接2个或多个字符串
	localeCompare()
		用本地特定的顺序来比较两个字符串
		//字符串1.localeCompare(字符串2)
	split()
		把一个字符串分割成字符串数组
	substring()
		提取字符串中的某一部分字符串
		//字符串.substring(开始位置,结束位置)